### ISSUE TITLE
Mouse example doesn't validate with given schema

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/data_schema#2]
It looks like `Genotype` is given as a required property in the schema, but only `Full Genotype` is found in the example.

Using validate module from jsonschema package and Python 3.8:

```
>>> validate(instance=mouse_296929, schema=ephys_mouse_schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jon.young/miniconda3/envs/test-schema/lib/python3.8/site-packages/jsonschema/validators.py", line 1022, in validate
    raise error
jsonschema.exceptions.ValidationError: 'Genotype' is a required property

Failed validating 'required' in schema:
    {'properties': {'Background Strain': {'enum': ['C57BL/6J', 'BALB/c'],
                                          'type': 'string'},
                    'Date of Birth': {'format': 'date', 'type': 'string'},
                    'Genotype': {'type': 'string'},
                    'Sex': {'enum': ['Female', 'Male'], 'type': 'string'},
                    'Source': {'type': 'string'},
                    'Specimen ID': {'type': 'integer'}},
     'required': ['Specimen ID',
                  'Sex',
                  'Date of Birth',
                  'Genotype',
                  'Background Strain'],
     'type': 'object'}

On instance:
    {'Background Strain': 'C57BL/6J',
     'Date of Birth': '2022-01-01',
     'Full Genotype': 'wt/wt',
     'Sex': 'Female',
     'Specimen ID': 296929}
```

**Comment by saskiad** [comment]
fixed the example. thanks!
