### ISSUE TITLE
Session example doesn't validate with given schema

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/data_schema#3]
An error is thrown when validating the session001 example with the Session schema. Might be an issue with the python package used to validate? (Python 3.8, jsonschema package, validate module)

```
>>> validate(instance=session001, schema=ephys_session_schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jon.young/miniconda3/envs/test-schema/lib/python3.8/site-packages/jsonschema/validators.py", line 1018, in validate
    cls.check_schema(schema)
  File "/home/jon.young/miniconda3/envs/test-schema/lib/python3.8/site-packages/jsonschema/validators.py", line 190, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: 'float' is not valid under any of the given schemas

Failed validating 'anyOf' in metaschema['allOf'][1]['properties']['properties']['additionalProperties']['$dynamicRef']['allOf'][3]['properties']['type']:
    {'anyOf': [{'$ref': '#/$defs/simpleTypes'},
               {'items': {'$ref': '#/$defs/simpleTypes'},
                'minItems': 1,
                'type': 'array',
                'uniqueItems': True}]}

On schema['properties']['Rig ID']['type']:
    'float'

```

**Comment by jtyoung84** [comment]
Following http://json-schema.org/, the python package jsonschema recognizes `number` as a basic type instead of `float`. I think that's the cause of this validation error.

**Comment by saskiad** [comment]
indeed. I need to fix it in a bunch of places - I'm on it.

**Comment by saskiad** [comment]
fixed
